# Generated by Django 4.2.2 on 2023-07-31 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_userprofile_avatarusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvatarUsuario',
        ),
    ]
