# Generated by Django 4.2.2 on 2023-07-24 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0002_rename_categoria_seguro_seccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segurocategoria',
            old_name='seccion',
            new_name='riesgo',
        ),
        migrations.AddField(
            model_name='seguro',
            name='riesgo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Seguros.segurocategoria'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='seccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
