# Generated by Django 4.2.2 on 2023-07-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0003_rename_seccion_segurocategoria_riesgo_seguro_riesgo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seguro',
            new_name='Seguros',
        ),
        migrations.RenameModel(
            old_name='SeguroCategoria',
            new_name='SegurosCategoria',
        ),
    ]
