# Generated by Django 4.2.2 on 2023-07-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0004_rename_seguro_seguros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguros',
            name='foto_inspeccion',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
