# Generated by Django 4.2.2 on 2023-07-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0005_seguros_foto_inspeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguros',
            name='foto_inspeccion',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_inspeccion'),
        ),
    ]
