# Generated by Django 4.2.2 on 2023-08-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0008_alter_seguros_foto_inspeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguros',
            name='foto_inspeccion',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
