# Generated by Django 4.2.2 on 2023-08-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0009_alter_seguros_foto_inspeccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seguros',
            old_name='foto_inspeccion',
            new_name='fotos_inspeccion',
        ),
    ]
