# Generated by Django 4.2.2 on 2023-08-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seguros', '0011_rename_fotos_inspeccion_seguros_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguros',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_inspeccion'),
        ),
    ]
