# Generated by Django 4.2.2 on 2023-07-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_rename_cliente_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
